# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78a7c3285bcf7d79e22c404b92f52d1a1a7d9d98ed295e24c4f490c50211e35ce7e06e728bc9acbc17d066d7f50e7c8bd5f2213ed639e6c90308e1994f5f3c56

test:
  secret_key_base: e3733cb352a681d798c047508b43fc26c1ff752a395739500a36f2b22495fa4f5b1fd694c0998966b5b69b5177294d6817755e1bf37ff2ae71dda06f22a0fcb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
